server:
  port: 8082

spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:ead_course}'
    username: ${DATABASE_USER:${DB_USER}}
    password: ${DATABASE_PASSWORD:${DB_PASSWORD}}

  output:
    ansi:
      enabled: Always

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
